---
name: CI
on:
  [push, pull_request]
env:
  DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: CIprep
        run: ./tools/scripts/ci/010_ciprep
      - name: CIbuild
        run: ./tools/scripts/ci/030_cibuild
      - name: CItest-iphone11
        run: |
          xcodebuild clean test \
          -project EN.xcodeproj \
          -scheme ENCore \
          -destination "platform=iOS Simulator,OS=latest,name=iPhone 11" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          ONLY_ACTIVE_ARCH=NO
        with: 
          xcode-version: 12.0
      - name: CIartifacts
        uses: actions/upload-artifact@v2
        with:
          name: buildinfo
          path: .buildinfo
