---
name: CI
on:
  [push, pull_request]

jobs:
  build:
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: CIprep
        run: ./tools/scripts/ci/010_ciprep
      - name: CIbuild
        run: ./tools/scripts/ci/030_cibuild
      - name: CItest-iphone11
        run: |
          sudo xcode-select -s /Applications/Xcode_11.7.app
          xcodebuild clean test \
          -version \
          -project EN.xcodeproj \
          -scheme ENCore \
          -destination "platform=iOS Simulator,OS=latest,name=iPhone 11" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          ONLY_ACTIVE_ARCH=NO
      - name: CIartifacts
        uses: actions/upload-artifact@v2
        with:
          name: buildinfo
          path: .buildinfo
